
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Embedded/STM32CubeCLT/STM32CubeCLT_1.19.0/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic - 1 - 
      The host system is: Windows - 10.0.26100 - AMD64
...
