/**
 * @file bsp_i2c.c
 * @brief I2C Wrapper Implementation using STM32 HAL
 * @author ARA Project Coder
 */

#include "bsp_i2c.h"
#include "stm32f1xx_hal.h"

/* --- Hardware Resources --- */
// External handle declaration (generated by CubeMX in main.c)
extern I2C_HandleTypeDef hi2c1;

// Internal mapping to HAL handles
static I2C_HandleTypeDef* i2c_handles[BSP_I2C_NUM] = {
        [BSP_I2C_MOTION] = &hi2c1
};

/* --- Callback Registry --- */
static AraCallback_t i2c_rx_cplt_cbs[BSP_I2C_NUM] = { NULL };

/* --- Helper: Status Conversion --- */
static AraStatus_t HAL_To_ARA_Status(HAL_StatusTypeDef status) {
    switch (status) {
        case HAL_OK:      return ARA_OK;
        case HAL_BUSY:    return ARA_BUSY;
        case HAL_TIMEOUT: return ARA_TIMEOUT;
        default:          return ARA_ERR_IO;
    }
}

/* --- API Implementation --- */

void BSP_I2C_Init(void)
{
    // Implementation Note:
    // In STM32 CubeMX workflow, HAL_I2C_Init() is usually called in main.c.
    // This function can be used to reset bus state or verify init if needed.
    // For now, we assume hardware is initialized by system boot.
}

AraStatus_t BSP_I2C_ReadMem(BspI2c_Dev_t dev, uint16_t dev_addr, uint16_t reg_addr, uint8_t *p_data, uint16_t len)
{
    if (dev >= BSP_I2C_NUM) return ARA_ERR_PARAM;

    // Use default timeout of 10ms for blocking calls
    HAL_StatusTypeDef status = HAL_I2C_Mem_Read(
            i2c_handles[dev],
            dev_addr,
            reg_addr,
            I2C_MEMADD_SIZE_8BIT, // Defaulting to 8-bit register addresses common for AS5600
            p_data,
            len,
            10
    );

    return HAL_To_ARA_Status(status);
}

AraStatus_t BSP_I2C_WriteMem(BspI2c_Dev_t dev, uint16_t dev_addr, uint16_t reg_addr, uint8_t *p_data, uint16_t len)
{
    if (dev >= BSP_I2C_NUM) return ARA_ERR_PARAM;

    HAL_StatusTypeDef status = HAL_I2C_Mem_Write(
            i2c_handles[dev],
            dev_addr,
            reg_addr,
            I2C_MEMADD_SIZE_8BIT,
            p_data,
            len,
            10
    );

    return HAL_To_ARA_Status(status);
}

AraStatus_t BSP_I2C_IsDeviceReady(BspI2c_Dev_t dev, uint16_t dev_addr)
{
    if (dev >= BSP_I2C_NUM) return ARA_ERR_PARAM;

    // Check if device acknowledges (Trial count: 2, Timeout: 2ms)
    HAL_StatusTypeDef status = HAL_I2C_IsDeviceReady(i2c_handles[dev], dev_addr, 2, 2);

    if (status == HAL_OK) {
        return ARA_OK;
    } else {
        return ARA_ERR_NACK;
    }
}

/* === DMA Support === */

void BSP_I2C_SetRxCpltCallback(BspI2c_Dev_t dev, AraCallback_t cb)
{
    if (dev < BSP_I2C_NUM) {
        i2c_rx_cplt_cbs[dev] = cb;
    }
}

AraStatus_t BSP_I2C_ReadMem_DMA(BspI2c_Dev_t dev, uint16_t dev_addr, uint16_t reg_addr, uint8_t *p_data, uint16_t len)
{
    if (dev >= BSP_I2C_NUM) return ARA_ERR_PARAM;

    HAL_StatusTypeDef status = HAL_I2C_Mem_Read_DMA(
            i2c_handles[dev],
            dev_addr,
            reg_addr,
            I2C_MEMADD_SIZE_8BIT,
            p_data,
            len
    );

    // Map specific DMA errors
    if (status == HAL_ERROR) return ARA_ERR_DMA;

    return HAL_To_ARA_Status(status);
}

/* --- HAL ISR Hook --- */
/**
 * @brief  Memory Read Complete Callback.
 * @note   This function overrides the weak definition in stm32f1xx_hal_i2c.c
 * It is called from the I2C Event IRQ Handler.
 */
void HAL_I2C_MemRxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    // Iterate to find which logical device triggered this
    for (int i = 0; i < BSP_I2C_NUM; i++) {
        if (i2c_handles[i] == hi2c) {
            // Found the device, execute callback if registered
            if (i2c_rx_cplt_cbs[i] != NULL) {
                i2c_rx_cplt_cbs[i]();
            }
            return;
        }
    }
}