/**
 * @file app_threads.c
 * @brief Top-level physical thread container and scheduler (L5) implementation.
 * @note  Strictly C99. Assembles L4 runnables into FreeRTOS physical threads.
 *        This revision keeps the dual-thread architecture unchanged and adds:
 *        1) a standard low-frequency readback point for DataHub state;
 *        2) throttled bring-up logs emitted only from the low-frequency thread.
 */

#include "app_threads.h"
#include "datahub.h"

/* L4 Business Logic Runnables */
#include "task_motion.h"
#include "task_manipulator.h"
#include "task_rc.h"
//#include "task_mock_vision.h"

/* FreeRTOS Dependencies */
#include "FreeRTOS.h"
#include "task.h"

/* BSP / Hardware Services */
#include "dev_status.h"
#include "bsp_uart.h"

/* ============================================================================
 * 1. Local Configuration
 * ========================================================================== */

/**
 * @brief Enable low-frequency bring-up logs on the debug/extension UART.
 * @note  Logging is intentionally placed only in the 50Hz thread to avoid
 *        disturbing the 1000Hz control pipeline.
 */
#define APP_THREADS_ENABLE_BRINGUP_LOG       (1)

/**
 * @brief Bring-up log interval in low-frequency thread ticks.
 * @note  Low-frequency thread period = 20ms.
 *        5 ticks = 100ms log interval.
 */
#define APP_THREADS_LOG_INTERVAL_TICKS       (5U)

/* ============================================================================
 * 2. Thread Handles
 * ========================================================================== */

/**
 * @brief Handle of the high-frequency control thread.
 */
static TaskHandle_t s_high_freq_task_handle = NULL;

/**
 * @brief Handle of the low-frequency logic thread.
 */
static TaskHandle_t s_low_freq_task_handle  = NULL;

/* ============================================================================
 * 3. Private Helper Functions
 * ========================================================================== */

#if APP_THREADS_ENABLE_BRINGUP_LOG

/**
 * @brief  Emit a throttled bring-up status line on the debug UART.
 * @param  tick_counter    Current low-frequency thread tick counter.
 * @param  p_cmd           Latest downlink command generated by the low-frequency logic.
 * @param  p_motion_state  Latest uplink state read back from the 1000Hz motion thread.
 * @note   Intended for bench bring-up only. The log format is compact and
 *         intentionally limited to one line every APP_THREADS_LOG_INTERVAL_TICKS.
 */
static void AppThreads_LogBringup(uint32_t tick_counter,
                                  const DataHub_Cmd_t *p_cmd,
                                  const DataHub_State_t *p_motion_state)
{
    if ((p_cmd == NULL) || (p_motion_state == NULL)) {
        return;
    }

    if ((tick_counter % APP_THREADS_LOG_INTERVAL_TICKS) != 0U) {
        return;
    }

    BSP_UART_Printf("[L5] mode=%d estop=%d tgt=%u cur=%u vel=%d foc=%d\r\n",
                    (int)p_cmd->sys_mode,
                    (int)p_cmd->emergency_stop,
                    (unsigned int)p_cmd->target_foc_angle,
                    (unsigned int)p_motion_state->current_foc_angle,
                    (int)p_motion_state->current_velocity,
                    (int)p_motion_state->foc_status);
}

#endif /* APP_THREADS_ENABLE_BRINGUP_LOG */

/**
 * @brief  Toggle the status LED according to the current system command state.
 * @param  p_cmd Pointer to the latest downlink command.
 * @param  led_tick_counter Monotonic counter running in the 50Hz thread.
 * @note   The LED policy remains simple:
 *         - Error / E-Stop: fast blink
 *         - Auto mode: medium heartbeat
 *         - Idle / Manual / other: slow blink
 */
static void AppThreads_UpdateStatusLed(const DataHub_Cmd_t *p_cmd,
                                       uint32_t led_tick_counter)
{
    if (p_cmd == NULL) {
        return;
    }

    if (p_cmd->emergency_stop || (p_cmd->sys_mode == ARA_MODE_ERROR)) {
        /* Error: fast blink, toggle every 2 ticks => ~80ms period */
        if ((led_tick_counter % 2U) == 0U) {
            DEV_Status_LED_ToggleLed();
        }
    } else if (p_cmd->sys_mode == ARA_MODE_AUTO) {
        /* Auto: medium heartbeat, toggle every 10 ticks => ~400ms period */
        if ((led_tick_counter % 10U) == 0U) {
            DEV_Status_LED_ToggleLed();
        }
    } else {
        /* Idle / Manual / other: slow blink, toggle every 50 ticks => ~2s period */
        if ((led_tick_counter % 50U) == 0U) {
            DEV_Status_LED_ToggleLed();
        }
    }
}

/* ============================================================================
 * 4. Physical Thread Entry Functions
 * ========================================================================== */

/**
 * @brief High-frequency control thread (1000Hz).
 * @param argument Unused thread argument.
 * @note  Priority: realtime.
 *         Pure motion pipeline:
 *         DataHub ReadCmd -> TaskMotion_Update -> DataHub WriteState.
 *         Absolutely no blocking or formatted logging is allowed here.
 */
static void Thread_HighFreq_Ctrl(void *argument)
{
    TickType_t xLastWakeTime = xTaskGetTickCount();
    const TickType_t xFrequency = pdMS_TO_TICKS(THREAD_HIGH_FREQ_PERIOD_MS);

    DataHub_Cmd_t   in_cmd;
    DataHub_State_t out_state;

    (void)argument;

    for (;;)
    {
        /* 1. Pull latest command from the low-frequency logic thread */
        DataHub_ReadCmd(&in_cmd);

        /* 2. Execute the 1000Hz motion pipeline */
        TaskMotion_Update(&in_cmd, &out_state);

        /* 3. Publish the latest hardware state to the DataHub */
        DataHub_WriteState(&out_state);

        /* 4. Strict periodic sleep */
        vTaskDelayUntil(&xLastWakeTime, xFrequency);
    }
}

/**
 * @brief Low-frequency logic thread (50Hz).
 * @param argument Unused thread argument.
 * @note  Priority: normal / above-normal.
 *         Standard pipeline:
 *         RC/Vision gather -> Motion readback -> Decision -> DataHub WriteCmd
 *         -> Status LED -> Optional bring-up log.
 * @note  The motion readback point is intentionally kept even if it is not yet
 *         consumed by TaskManipulator_Update(). This reserves a clean insertion
 *         point for future state-aware AUTO logic.
 */
static void Thread_LowFreq_Logic(void *argument)
{
    TickType_t xLastWakeTime = xTaskGetTickCount();
    const TickType_t xFrequency = pdMS_TO_TICKS(THREAD_LOW_FREQ_PERIOD_MS);

    RcControlData_t rc_intent;
//    AraVisionData_t vision_data;
    DataHub_State_t motion_state;
    DataHub_Cmd_t   out_cmd;

    uint32_t low_freq_tick_counter = 0U;

    (void)argument;

    for (;;)
    {
        uint32_t current_tick_ms = (uint32_t)xTaskGetTickCount();

        /* Defensive reinitialization of local pipeline buffers */
        rc_intent.is_link_up      = false;
        rc_intent.req_mode        = ARA_MODE_INIT;
        rc_intent.estop_state     = ESTOP_RELEASED;
        rc_intent.arm_cmd         = ARM_CMD_HOLD;
        rc_intent.gripper_cmd     = GRIPPER_CMD_STOP;
        rc_intent.sys_reset_pulse = false;
        rc_intent.aux_knob_val    = 0U;

//        vision_data.seq_id         = 0U;
//        vision_data.is_tracking    = false;
//        vision_data.is_grabbable   = false;
//        vision_data.pc_estop_req   = false;
//        vision_data.target_roll    = 0;
//        vision_data.target_dist_mm = 0U;

        out_cmd.sys_mode         = ARA_MODE_INIT;
        out_cmd.emergency_stop   = true;
        out_cmd.target_foc_angle = 0U;

        motion_state.current_foc_angle = 0U;
        motion_state.current_velocity  = 0;
        motion_state.foc_status        = ARA_ERROR;

        low_freq_tick_counter++;

        /* ====================================================================
         * STAGE 1: Perception (Gather Inputs)
         * ================================================================== */

        /* 1A. Fetch RC semantic intent */
        TaskRc_Update(current_tick_ms, &rc_intent);

        /* 1B. Fetch latest vision data */
#if ENABLE_MOCK_VISION
//        TaskMockVision_Update(current_tick_ms, &vision_data);
#else
        /* Placeholder for the real UART VSP runnable */
        /* TaskVision_Update(current_tick_ms, &vision_data); */
#endif

        /* 1C. Read back the latest motion state from the 1000Hz control thread
         *     This is currently used for bring-up observability and is the
         *     reserved insertion point for future state-aware AUTO logic.
         */
        DataHub_ReadState(&motion_state);

        /* ====================================================================
         * STAGE 2: Decision (State Machine)
         * ================================================================== */

        /* Generate command for the high-frequency motion thread */
        TaskManipulator_Update(&rc_intent, &motion_state, &out_cmd);

        /* ====================================================================
         * STAGE 3: Action (Publish Command)
         * ================================================================== */

        DataHub_WriteCmd(&out_cmd);

        /* ====================================================================
         * STAGE 4: Status LED / Bring-up Observability
         * ================================================================== */

        AppThreads_UpdateStatusLed(&out_cmd, low_freq_tick_counter);

#if APP_THREADS_ENABLE_BRINGUP_LOG
        AppThreads_LogBringup(low_freq_tick_counter, &out_cmd, &motion_state);
#endif

        /* ====================================================================
         * STAGE 5: Strict 50Hz Sleep
         * ================================================================== */

        vTaskDelayUntil(&xLastWakeTime, xFrequency);
    }
}

/* ============================================================================
 * 5. Public API Implementation
 * ========================================================================== */

/**
 * @brief Initialize the global blackboard, L4 runnables, and the two physical threads.
 * @note  Initialization order:
 *         1) DataHub
 *         2) L4 runnables
 *         3) Mock Vision (if enabled)
 *         4) FreeRTOS task creation
 */
void App_Threads_Init(void)
{
    /* 1. Initialize the global lock-free blackboard first */
    DataHub_Init();

    /* 2. Initialize L4 business modules */
    TaskMotion_Init();
    TaskRc_Init();
    TaskManipulator_Init();

#if ENABLE_MOCK_VISION
//    TaskMockVision_Init();
//    TaskMockVision_SetScenario(MOCK_SCENARIO_HAPPY_PATH);
#else
    /* TaskVision_Init(); */
#endif

    /* 3. Mount physical threads to the FreeRTOS scheduler */
    xTaskCreate(Thread_HighFreq_Ctrl,
                "HighFreqCtrl",
                THREAD_HIGH_FREQ_STACK,
                NULL,
                configMAX_PRIORITIES - 1,
                &s_high_freq_task_handle);

    xTaskCreate(Thread_LowFreq_Logic,
                "LowFreqLogic",
                THREAD_LOW_FREQ_STACK,
                NULL,
                configMAX_PRIORITIES - 3,
                &s_low_freq_task_handle);
}